import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google"
import localFont from "next/font/local";
import "./globals.css";

const playfair = Playfair_Display({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Approve It",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
